/**
 * generated by Xtext 2.25.0
 */
package br.ufrn.ppgti.ppgti1007.salarioLiquido;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Salario</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufrn.ppgti.ppgti1007.salarioLiquido.Salario#getValor <em>Valor</em>}</li>
 *   <li>{@link br.ufrn.ppgti.ppgti1007.salarioLiquido.Salario#getDependentes <em>Dependentes</em>}</li>
 *   <li>{@link br.ufrn.ppgti.ppgti1007.salarioLiquido.Salario#getDescontos <em>Descontos</em>}</li>
 *   <li>{@link br.ufrn.ppgti.ppgti1007.salarioLiquido.Salario#getPrevidencia <em>Previdencia</em>}</li>
 * </ul>
 *
 * @see br.ufrn.ppgti.ppgti1007.salarioLiquido.SalarioLiquidoPackage#getSalario()
 * @model
 * @generated
 */
public interface Salario extends EObject
{
  /**
   * Returns the value of the '<em><b>Valor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valor</em>' attribute.
   * @see #setValor(double)
   * @see br.ufrn.ppgti.ppgti1007.salarioLiquido.SalarioLiquidoPackage#getSalario_Valor()
   * @model
   * @generated
   */
  double getValor();

  /**
   * Sets the value of the '{@link br.ufrn.ppgti.ppgti1007.salarioLiquido.Salario#getValor <em>Valor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Valor</em>' attribute.
   * @see #getValor()
   * @generated
   */
  void setValor(double value);

  /**
   * Returns the value of the '<em><b>Dependentes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dependentes</em>' attribute.
   * @see #setDependentes(int)
   * @see br.ufrn.ppgti.ppgti1007.salarioLiquido.SalarioLiquidoPackage#getSalario_Dependentes()
   * @model
   * @generated
   */
  int getDependentes();

  /**
   * Sets the value of the '{@link br.ufrn.ppgti.ppgti1007.salarioLiquido.Salario#getDependentes <em>Dependentes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dependentes</em>' attribute.
   * @see #getDependentes()
   * @generated
   */
  void setDependentes(int value);

  /**
   * Returns the value of the '<em><b>Descontos</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Descontos</em>' attribute.
   * @see #setDescontos(double)
   * @see br.ufrn.ppgti.ppgti1007.salarioLiquido.SalarioLiquidoPackage#getSalario_Descontos()
   * @model
   * @generated
   */
  double getDescontos();

  /**
   * Sets the value of the '{@link br.ufrn.ppgti.ppgti1007.salarioLiquido.Salario#getDescontos <em>Descontos</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Descontos</em>' attribute.
   * @see #getDescontos()
   * @generated
   */
  void setDescontos(double value);

  /**
   * Returns the value of the '<em><b>Previdencia</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Previdencia</em>' attribute.
   * @see #setPrevidencia(double)
   * @see br.ufrn.ppgti.ppgti1007.salarioLiquido.SalarioLiquidoPackage#getSalario_Previdencia()
   * @model
   * @generated
   */
  double getPrevidencia();

  /**
   * Sets the value of the '{@link br.ufrn.ppgti.ppgti1007.salarioLiquido.Salario#getPrevidencia <em>Previdencia</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Previdencia</em>' attribute.
   * @see #getPrevidencia()
   * @generated
   */
  void setPrevidencia(double value);

} // Salario
