/**
 * generated by Xtext 2.25.0
 */
package br.ufrn.ppgti.ppgti1007.salarioLiquido;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Salarios</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufrn.ppgti.ppgti1007.salarioLiquido.Salarios#getSalarios <em>Salarios</em>}</li>
 * </ul>
 *
 * @see br.ufrn.ppgti.ppgti1007.salarioLiquido.SalarioLiquidoPackage#getSalarios()
 * @model
 * @generated
 */
public interface Salarios extends EObject
{
  /**
   * Returns the value of the '<em><b>Salarios</b></em>' containment reference list.
   * The list contents are of type {@link br.ufrn.ppgti.ppgti1007.salarioLiquido.Salario}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Salarios</em>' containment reference list.
   * @see br.ufrn.ppgti.ppgti1007.salarioLiquido.SalarioLiquidoPackage#getSalarios_Salarios()
   * @model containment="true"
   * @generated
   */
  EList<Salario> getSalarios();

} // Salarios
