/**
 * generated by Xtext 2.25.0
 */
package br.ufrn.ppgti.ppgti1007.salarioLiquido;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see br.ufrn.ppgti.ppgti1007.salarioLiquido.SalarioLiquidoPackage
 * @generated
 */
public interface SalarioLiquidoFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SalarioLiquidoFactory eINSTANCE = br.ufrn.ppgti.ppgti1007.salarioLiquido.impl.SalarioLiquidoFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Salarios</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Salarios</em>'.
   * @generated
   */
  Salarios createSalarios();

  /**
   * Returns a new object of class '<em>Salario</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Salario</em>'.
   * @generated
   */
  Salario createSalario();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  SalarioLiquidoPackage getSalarioLiquidoPackage();

} //SalarioLiquidoFactory
