/*
 * generated by Xtext 2.25.0
 */
package br.ufrn.ppgti.ppgti1007.ui;

import br.ufrn.ppgti.ppgti1007.SalarioLiquido.ui.internal.SalarioLiquidoActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SalarioLiquidoExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SalarioLiquidoActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SalarioLiquidoActivator activator = SalarioLiquidoActivator.getInstance();
		return activator != null ? activator.getInjector(SalarioLiquidoActivator.BR_UFRN_PPGTI_PPGTI1007_SALARIOLIQUIDO) : null;
	}

}
