/**
 * generated by Xtext 2.25.0
 */
package br.ufrn.ppgti.ppgti1007.salarioLiquido.impl;

import br.ufrn.ppgti.ppgti1007.salarioLiquido.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class SalarioLiquidoFactoryImpl extends EFactoryImpl implements SalarioLiquidoFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static SalarioLiquidoFactory init()
  {
    try
    {
      SalarioLiquidoFactory theSalarioLiquidoFactory = (SalarioLiquidoFactory)EPackage.Registry.INSTANCE.getEFactory(SalarioLiquidoPackage.eNS_URI);
      if (theSalarioLiquidoFactory != null)
      {
        return theSalarioLiquidoFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new SalarioLiquidoFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SalarioLiquidoFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case SalarioLiquidoPackage.SALARIOS: return createSalarios();
      case SalarioLiquidoPackage.SALARIO: return createSalario();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Salarios createSalarios()
  {
    SalariosImpl salarios = new SalariosImpl();
    return salarios;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Salario createSalario()
  {
    SalarioImpl salario = new SalarioImpl();
    return salario;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SalarioLiquidoPackage getSalarioLiquidoPackage()
  {
    return (SalarioLiquidoPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static SalarioLiquidoPackage getPackage()
  {
    return SalarioLiquidoPackage.eINSTANCE;
  }

} //SalarioLiquidoFactoryImpl
