/**
 * generated by Xtext 2.25.0
 */
package br.ufrn.ppgti.ppgti1007.salarioLiquido.impl;

import br.ufrn.ppgti.ppgti1007.salarioLiquido.Salario;
import br.ufrn.ppgti.ppgti1007.salarioLiquido.SalarioLiquidoFactory;
import br.ufrn.ppgti.ppgti1007.salarioLiquido.SalarioLiquidoPackage;
import br.ufrn.ppgti.ppgti1007.salarioLiquido.Salarios;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class SalarioLiquidoPackageImpl extends EPackageImpl implements SalarioLiquidoPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass salariosEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass salarioEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see br.ufrn.ppgti.ppgti1007.salarioLiquido.SalarioLiquidoPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private SalarioLiquidoPackageImpl()
  {
    super(eNS_URI, SalarioLiquidoFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link SalarioLiquidoPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static SalarioLiquidoPackage init()
  {
    if (isInited) return (SalarioLiquidoPackage)EPackage.Registry.INSTANCE.getEPackage(SalarioLiquidoPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredSalarioLiquidoPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    SalarioLiquidoPackageImpl theSalarioLiquidoPackage = registeredSalarioLiquidoPackage instanceof SalarioLiquidoPackageImpl ? (SalarioLiquidoPackageImpl)registeredSalarioLiquidoPackage : new SalarioLiquidoPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theSalarioLiquidoPackage.createPackageContents();

    // Initialize created meta-data
    theSalarioLiquidoPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theSalarioLiquidoPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(SalarioLiquidoPackage.eNS_URI, theSalarioLiquidoPackage);
    return theSalarioLiquidoPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSalarios()
  {
    return salariosEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSalarios_Salarios()
  {
    return (EReference)salariosEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSalario()
  {
    return salarioEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSalario_Valor()
  {
    return (EAttribute)salarioEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSalario_Dependentes()
  {
    return (EAttribute)salarioEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSalario_Descontos()
  {
    return (EAttribute)salarioEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSalario_Previdencia()
  {
    return (EAttribute)salarioEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SalarioLiquidoFactory getSalarioLiquidoFactory()
  {
    return (SalarioLiquidoFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    salariosEClass = createEClass(SALARIOS);
    createEReference(salariosEClass, SALARIOS__SALARIOS);

    salarioEClass = createEClass(SALARIO);
    createEAttribute(salarioEClass, SALARIO__VALOR);
    createEAttribute(salarioEClass, SALARIO__DEPENDENTES);
    createEAttribute(salarioEClass, SALARIO__DESCONTOS);
    createEAttribute(salarioEClass, SALARIO__PREVIDENCIA);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(salariosEClass, Salarios.class, "Salarios", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSalarios_Salarios(), this.getSalario(), null, "salarios", null, 0, -1, Salarios.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(salarioEClass, Salario.class, "Salario", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSalario_Valor(), ecorePackage.getEDouble(), "valor", null, 0, 1, Salario.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSalario_Dependentes(), ecorePackage.getEInt(), "dependentes", null, 0, 1, Salario.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSalario_Descontos(), ecorePackage.getEDouble(), "descontos", null, 0, 1, Salario.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSalario_Previdencia(), ecorePackage.getEDouble(), "previdencia", null, 0, 1, Salario.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //SalarioLiquidoPackageImpl
