/**
 * generated by Xtext 2.25.0
 */
package br.ufrn.ppgti.ppgti1007.salarioLiquido.impl;

import br.ufrn.ppgti.ppgti1007.salarioLiquido.Salario;
import br.ufrn.ppgti.ppgti1007.salarioLiquido.SalarioLiquidoPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Salario</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufrn.ppgti.ppgti1007.salarioLiquido.impl.SalarioImpl#getValor <em>Valor</em>}</li>
 *   <li>{@link br.ufrn.ppgti.ppgti1007.salarioLiquido.impl.SalarioImpl#getDependentes <em>Dependentes</em>}</li>
 *   <li>{@link br.ufrn.ppgti.ppgti1007.salarioLiquido.impl.SalarioImpl#getDescontos <em>Descontos</em>}</li>
 *   <li>{@link br.ufrn.ppgti.ppgti1007.salarioLiquido.impl.SalarioImpl#getPrevidencia <em>Previdencia</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SalarioImpl extends MinimalEObjectImpl.Container implements Salario
{
  /**
   * The default value of the '{@link #getValor() <em>Valor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValor()
   * @generated
   * @ordered
   */
  protected static final double VALOR_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getValor() <em>Valor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValor()
   * @generated
   * @ordered
   */
  protected double valor = VALOR_EDEFAULT;

  /**
   * The default value of the '{@link #getDependentes() <em>Dependentes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDependentes()
   * @generated
   * @ordered
   */
  protected static final int DEPENDENTES_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getDependentes() <em>Dependentes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDependentes()
   * @generated
   * @ordered
   */
  protected int dependentes = DEPENDENTES_EDEFAULT;

  /**
   * The default value of the '{@link #getDescontos() <em>Descontos</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescontos()
   * @generated
   * @ordered
   */
  protected static final double DESCONTOS_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getDescontos() <em>Descontos</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescontos()
   * @generated
   * @ordered
   */
  protected double descontos = DESCONTOS_EDEFAULT;

  /**
   * The default value of the '{@link #getPrevidencia() <em>Previdencia</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrevidencia()
   * @generated
   * @ordered
   */
  protected static final double PREVIDENCIA_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getPrevidencia() <em>Previdencia</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrevidencia()
   * @generated
   * @ordered
   */
  protected double previdencia = PREVIDENCIA_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SalarioImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SalarioLiquidoPackage.Literals.SALARIO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getValor()
  {
    return valor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setValor(double newValor)
  {
    double oldValor = valor;
    valor = newValor;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SalarioLiquidoPackage.SALARIO__VALOR, oldValor, valor));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getDependentes()
  {
    return dependentes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDependentes(int newDependentes)
  {
    int oldDependentes = dependentes;
    dependentes = newDependentes;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SalarioLiquidoPackage.SALARIO__DEPENDENTES, oldDependentes, dependentes));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getDescontos()
  {
    return descontos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescontos(double newDescontos)
  {
    double oldDescontos = descontos;
    descontos = newDescontos;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SalarioLiquidoPackage.SALARIO__DESCONTOS, oldDescontos, descontos));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getPrevidencia()
  {
    return previdencia;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPrevidencia(double newPrevidencia)
  {
    double oldPrevidencia = previdencia;
    previdencia = newPrevidencia;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SalarioLiquidoPackage.SALARIO__PREVIDENCIA, oldPrevidencia, previdencia));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SalarioLiquidoPackage.SALARIO__VALOR:
        return getValor();
      case SalarioLiquidoPackage.SALARIO__DEPENDENTES:
        return getDependentes();
      case SalarioLiquidoPackage.SALARIO__DESCONTOS:
        return getDescontos();
      case SalarioLiquidoPackage.SALARIO__PREVIDENCIA:
        return getPrevidencia();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SalarioLiquidoPackage.SALARIO__VALOR:
        setValor((Double)newValue);
        return;
      case SalarioLiquidoPackage.SALARIO__DEPENDENTES:
        setDependentes((Integer)newValue);
        return;
      case SalarioLiquidoPackage.SALARIO__DESCONTOS:
        setDescontos((Double)newValue);
        return;
      case SalarioLiquidoPackage.SALARIO__PREVIDENCIA:
        setPrevidencia((Double)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SalarioLiquidoPackage.SALARIO__VALOR:
        setValor(VALOR_EDEFAULT);
        return;
      case SalarioLiquidoPackage.SALARIO__DEPENDENTES:
        setDependentes(DEPENDENTES_EDEFAULT);
        return;
      case SalarioLiquidoPackage.SALARIO__DESCONTOS:
        setDescontos(DESCONTOS_EDEFAULT);
        return;
      case SalarioLiquidoPackage.SALARIO__PREVIDENCIA:
        setPrevidencia(PREVIDENCIA_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SalarioLiquidoPackage.SALARIO__VALOR:
        return valor != VALOR_EDEFAULT;
      case SalarioLiquidoPackage.SALARIO__DEPENDENTES:
        return dependentes != DEPENDENTES_EDEFAULT;
      case SalarioLiquidoPackage.SALARIO__DESCONTOS:
        return descontos != DESCONTOS_EDEFAULT;
      case SalarioLiquidoPackage.SALARIO__PREVIDENCIA:
        return previdencia != PREVIDENCIA_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (valor: ");
    result.append(valor);
    result.append(", dependentes: ");
    result.append(dependentes);
    result.append(", descontos: ");
    result.append(descontos);
    result.append(", previdencia: ");
    result.append(previdencia);
    result.append(')');
    return result.toString();
  }

} //SalarioImpl
