/**
 * generated by Xtext 2.25.0
 */
package br.ufrn.ppgti.ppgti1007.salarioLiquido.impl;

import br.ufrn.ppgti.ppgti1007.salarioLiquido.Salario;
import br.ufrn.ppgti.ppgti1007.salarioLiquido.SalarioLiquidoPackage;
import br.ufrn.ppgti.ppgti1007.salarioLiquido.Salarios;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Salarios</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufrn.ppgti.ppgti1007.salarioLiquido.impl.SalariosImpl#getSalarios <em>Salarios</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SalariosImpl extends MinimalEObjectImpl.Container implements Salarios
{
  /**
   * The cached value of the '{@link #getSalarios() <em>Salarios</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSalarios()
   * @generated
   * @ordered
   */
  protected EList<Salario> salarios;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SalariosImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SalarioLiquidoPackage.Literals.SALARIOS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Salario> getSalarios()
  {
    if (salarios == null)
    {
      salarios = new EObjectContainmentEList<Salario>(Salario.class, this, SalarioLiquidoPackage.SALARIOS__SALARIOS);
    }
    return salarios;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SalarioLiquidoPackage.SALARIOS__SALARIOS:
        return ((InternalEList<?>)getSalarios()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SalarioLiquidoPackage.SALARIOS__SALARIOS:
        return getSalarios();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SalarioLiquidoPackage.SALARIOS__SALARIOS:
        getSalarios().clear();
        getSalarios().addAll((Collection<? extends Salario>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SalarioLiquidoPackage.SALARIOS__SALARIOS:
        getSalarios().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SalarioLiquidoPackage.SALARIOS__SALARIOS:
        return salarios != null && !salarios.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //SalariosImpl
