/*
 * generated by Xtext 2.25.0
 */
package br.ufrn.ppgti.ppgti1007.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSalarioLiquidoScopeProvider extends DelegatingScopeProvider {
}
