/*
 * generated by Xtext 2.25.0
 */
package br.ufrn.ppgti.ppgti1007.ide;

import br.ufrn.ppgti.ppgti1007.SalarioLiquidoRuntimeModule;
import br.ufrn.ppgti.ppgti1007.SalarioLiquidoStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SalarioLiquidoIdeSetup extends SalarioLiquidoStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SalarioLiquidoRuntimeModule(), new SalarioLiquidoIdeModule()));
	}
	
}
