/*
 * generated by Xtext 2.25.0
 */
package br.ufrn.ppgti.ppgti1007.ide;


/**
 * Use this class to register ide components.
 */
public class SalarioLiquidoIdeModule extends AbstractSalarioLiquidoIdeModule {
}
