/*
 * generated by Xtext 2.25.0
 */
package br.ufrn.ppgti.ppgti1007;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SalarioLiquidoRuntimeModule extends AbstractSalarioLiquidoRuntimeModule {
}
