/*
 * generated by Xtext 2.25.0
 */
package br.ufrn.ppgti.ppgti1007.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SalarioLiquidoUiModule extends AbstractSalarioLiquidoUiModule {

	public SalarioLiquidoUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
