/*
 * generated by Xtext 2.25.0
 */
package br.ufrn.ppgti.ppgti1007.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSalarioLiquidoValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(br.ufrn.ppgti.ppgti1007.salarioLiquido.SalarioLiquidoPackage.eINSTANCE);
		return result;
	}
}
