/*
 * generated by Xtext 2.25.0
 */
package br.ufrn.ppgti.ppgti1007.parser.antlr;

import br.ufrn.ppgti.ppgti1007.parser.antlr.internal.InternalSalarioLiquidoParser;
import br.ufrn.ppgti.ppgti1007.services.SalarioLiquidoGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SalarioLiquidoParser extends AbstractAntlrParser {

	@Inject
	private SalarioLiquidoGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSalarioLiquidoParser createParser(XtextTokenStream stream) {
		return new InternalSalarioLiquidoParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Salarios";
	}

	public SalarioLiquidoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SalarioLiquidoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
