/*
 * generated by Xtext 2.25.0
 */
package br.ufrn.ppgti.ppgti1007.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SalarioLiquidoAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("br/ufrn/ppgti/ppgti1007/parser/antlr/internal/InternalSalarioLiquido.tokens");
	}
}
